apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctorvit-redis
  namespace: doctorvit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctorvit-redis
  template:
    metadata:
      labels:
        app: doctorvit-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: doctorvit-redis
  namespace: doctorvit
spec:
  type: ClusterIP
  selector:
    app: doctorvit-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
