apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctorvit-worker
  namespace: doctorvit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctorvit-worker
  template:
    metadata:
      labels:
        app: doctorvit-worker
    spec:
      containers:
        - name: worker
          image: REPLACE_WITH_REGISTRY/doctorvit-transformers-worker:latest
          env:
            - name: MODEL_S3_URI
              valueFrom:
                secretKeyRef:
                  name: doctorvit-s3
                  key: MODEL_S3_URI
            - name: MODEL_LOCAL_PATH
              valueFrom:
                secretKeyRef:
                  name: doctorvit-s3
                  key: MODEL_LOCAL_PATH
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: doctorvit-s3
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: doctorvit-s3
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: doctorvit-s3
                  key: AWS_SECRET_ACCESS_KEY
            - name: REDIS_URL
              value: redis://doctorvit-redis:6379/0
          volumeMounts:
            - name: models
              mountPath: /models
          resources:
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: models
          emptyDir: {}
