apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: doctorvit-transformers-svc-hpa
  namespace: doctorvit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doctorvit-transformers-svc
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
