apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doctorvit.fullname" . }}-worker
  labels: {{- include "doctorvit.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "doctorvit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "doctorvit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.repository }}:{{ .Values.worker.tag }}"
          imagePullPolicy: {{ .Values.worker.pullPolicy }}
          command: ["celery","-A","app.celery_app.celery_app","worker","--loglevel=INFO","-Q","gpu","-c","1"]
          env:
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
              nvidia.com/gpu: {{ .Values.resources.requests."nvidia.com/gpu" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
              nvidia.com/gpu: {{ .Values.resources.limits."nvidia.com/gpu" }}
