version: "3.8"

services:
  api:
    build: .
    image: doctorvit/api:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8000
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - redis

  worker:
    build: .
    image: doctorvit/worker:latest
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO -Q gpu -c 1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
